<?php

$awardsContent = [
    'metaTitle' => 'CreatorX Awards 2026 | Influencer Awards in Hyderabad',
    'metaDescription' => '25+ award categories for Telugu creators across tech, food, travel, finance, comedy and more. Judged by an expert jury.',
    'bannerTitle' => 'CreatorX Awards 2026',
    'bannerText' => 'Celebrating the Telugu creators who move millions.',
    'intro' => 'The CreatorX Awards honour Telugu creators from both states and the NRI community across every platform — Instagram, YouTube, Facebook, X, LinkedIn, Moj, ShareChat and more. Winners are chosen by a jury of 10–12 industry experts and announced live at the Creators Conclave Summit in Hyderabad.',
    'dates' => [
        ['milestone' => 'Nominations open', 'date' => '1 October 2026'],
        ['milestone' => 'Nominations close', 'date' => '30 October 2026'],
        ['milestone' => 'Jury evaluation & shortlist', 'date' => '[November 2026 — confirm]'],
        ['milestone' => 'Awards night', 'date' => 'December 2026, Hyderabad'],
    ],
    'whoTitle' => 'Who can apply',
    'who' => [
        'Creators of Telugu origin, from Andhra Pradesh, Telangana or anywhere in the world (NRI).',
        'Active on any social media platform.',
        'One creator can enter up to 3 categories.',
    ],
    'categoriesTitle' => 'Award categories (proposed — client to approve)',
    'categories' => [
        ['Creator of the Year', 'The overall standout Telugu creator of the year'],
        ['Tech Creator of the Year', 'Clear, trusted tech reviews and explainers'],
        ['Food Creator of the Year', 'Recipes, food reviews and culinary storytelling'],
        ['Travel Creator of the Year', 'Travel content that inspires exploration'],
        ['Lifestyle Creator of the Year', 'Everyday living, home and personal style'],
        ['Fashion & Beauty Creator of the Year', 'Styling, beauty and grooming content'],
        ['Entertainment Creator of the Year', 'Content that keeps audiences hooked'],
        ['Comedy Creator of the Year', 'Sketches, skits and humour'],
        ['Education Creator of the Year', 'Learning content for students and professionals'],
        ['Finance Creator of the Year', 'Responsible personal finance and money content'],
        ['Legal Awareness Creator of the Year', 'Making law simple for everyday people'],
        ['Professional / Career Creator of the Year', 'Career, workplace and skill-building content'],
        ['Health & Fitness Creator of the Year', 'Fitness, wellness and healthy living'],
        ['Regional Culture Creator of the Year', 'Celebrating Telugu culture, tradition and language'],
        ['Music Creator of the Year', 'Original music, covers and performances'],
        ['Dance Creator of the Year', 'Choreography and dance content'],
        ['Parenting & Family Creator of the Year', 'Family and parenting content'],
        ['Devotional & Spiritual Creator of the Year', 'Spiritual and devotional content'],
        ['Agriculture & Rural Creator of the Year', 'Farming and rural-life content'],
        ['NRI Creator of the Year', 'A Telugu creator based outside India'],
        ['Emerging Creator of the Year', 'A fast-rising creator under 100K followers'],
        ['Best Brand Collaboration', 'The most effective creator-brand campaign'],
        ['Best Short-Form Content', 'Outstanding Reels / Shorts'],
        ['Best Podcast / Long-Form Creator', 'Podcasts, interviews and long-form video'],
        ['Social Impact Creator of the Year', 'Content that drives positive change'],
    ],
    'chosenTitle' => 'How winners are chosen',
    'chosen' => 'There is no public voting. Every eligible nomination is reviewed by our jury on originality, content quality, audience engagement, consistency and impact. The jury’s decision is final.',
    'cta' => 'Ready to take the stage?',
];
