<?php

$events = [
    [
        'slug' => 'summit-2026',
        'name' => 'Creators Conclave Summit',
        'type' => 'Creator Conferences',
        'location' => 'Assembly Hall, BKC, Mumbai',
        'city' => 'Mumbai',
        'date' => '20–22 November 2026',
        'dateShort' => '20–22 Nov 2026',
        'image' => 'images/events/summit.jpg',
        'summary' => 'The flagship gathering for YouTubers, founders, editors, and the teams who turn attention into culture.',
        'about' => 'Summit is the annual room where the creator economy slows down long enough to be honest. Three days of mainstage conversations, closed-door roundtables, and public sessions on craft, distribution, brand partnerships, and the business of an audience. It is built for people who publish, produce, and partner — not for spectators collecting lanyards.',
        'highlights' => [
            'Mainstage keynotes and creator-led panels',
            'Invitation roundtables for operators and editors',
            'Brand matching hours with structured briefs',
            'The Conclave Awards on the closing night',
        ],
        'schedule' => [
            ['time' => '20 Nov · 10:00', 'title' => 'Opening session', 'detail' => 'State of the creator economy, with publishers, platforms, and independent studios.'],
            ['time' => '20 Nov · 16:30', 'title' => 'After Hours', 'detail' => 'An off-record networking evening for speakers, partners, and accredited press.'],
            ['time' => '21 Nov · 11:00', 'title' => 'Craft laboratories', 'detail' => 'Workshops on formats, series design, and audience trust.'],
            ['time' => '21 Nov · 19:30', 'title' => 'Conclave Awards', 'detail' => 'Recognition for work that moved the industry, not just the algorithm.'],
            ['time' => '22 Nov · 14:00', 'title' => 'Partnership forum', 'detail' => 'Briefings between brands and creators with a shared point of view.'],
        ],
        'experiences' => [
            ['title' => 'Mainstage', 'detail' => 'A black-box hall for long conversations, not slogan panels.'],
            ['title' => 'The Edit Rooms', 'detail' => 'Small studios for teardowns of formats, thumbnails, and series arcs.'],
            ['title' => 'Closing gala', 'detail' => 'Awards, performances, and the people who actually made the year.'],
        ],
        'speakers' => ['mira-sen', 'arjun-vale', 'leela-nair', 'kabir-das', 'anika-rao'],
        'sponsors' => ['northline', 'lumen', 'framehouse', 'orbit'],
        'gallery' => ['images/gallery/auditorium.jpg', 'images/gallery/speaker.jpg', 'images/gallery/hands-up.jpg', 'images/events/awards.jpg'],
        'featured' => true,
    ],
    [
        'slug' => 'youtube-night',
        'name' => 'YouTube Creators Night',
        'type' => 'YouTube Events',
        'location' => 'Indiranagar Assembly, Bengaluru',
        'city' => 'Bengaluru',
        'date' => '8 December 2026',
        'dateShort' => '8 Dec 2026',
        'image' => 'images/events/youtube-night.jpg',
        'summary' => 'An evening for long-form creators, editors, and channel operators who still care about the watch.',
        'about' => 'Creators Night is a focused evening for people who make YouTube their primary stage. Screenings, format clinics, and a late conversation about what still earns an audience when the feed gets louder.',
        'highlights' => [
            'Format clinic with working editors',
            'Screening of standout long-form work',
            'Open floor for channel operators',
        ],
        'schedule' => [
            ['time' => '17:00', 'title' => 'Doors and reels wall', 'detail' => 'A silent cut of the year’s most precise openings.'],
            ['time' => '18:30', 'title' => 'Format clinic', 'detail' => 'Editors break down retention without the usual myths.'],
            ['time' => '20:30', 'title' => 'Night session', 'detail' => 'Creators in conversation, then an informal close.'],
        ],
        'experiences' => [
            ['title' => 'Edit wall', 'detail' => 'A looping installation of openings, titles, and cuts.'],
            ['title' => 'Operator table', 'detail' => 'Producers compare calendars, crews, and costs.'],
        ],
        'speakers' => ['kabir-das', 'jules-fernando', 'sana-iqbal'],
        'sponsors' => ['framehouse', 'pulse'],
        'gallery' => ['images/gallery/stage-rig.jpg', 'images/gallery/blue-stage.jpg', 'images/events/youtube-night.jpg'],
        'featured' => false,
    ],
    [
        'slug' => 'brand-forum',
        'name' => 'Brand × Creator Forum',
        'type' => 'Brand × Creator Events',
        'location' => 'Lodhi Assembly, New Delhi',
        'city' => 'New Delhi',
        'date' => '16 January 2027',
        'dateShort' => '16 Jan 2027',
        'image' => 'images/events/brand-forum.jpg',
        'summary' => 'A working forum where brand teams and creators write briefs that respect both the audience and the work.',
        'about' => 'The Forum is not a pitch carnival. Brand marketers, creators, and their producers sit with real constraints: disclosure, taste, timelines, and what an audience will actually trust. The day ends with paired working sessions, not a stack of leave-behinds.',
        'highlights' => [
            'Brief teardowns with brand and creator pairs',
            'Disclosure and taste roundtable',
            'Structured matching, not open networking chaos',
        ],
        'schedule' => [
            ['time' => '09:30', 'title' => 'Briefing', 'detail' => 'How a good collaboration is scoped before anyone films.'],
            ['time' => '12:00', 'title' => 'Paired sessions', 'detail' => 'Creators and brand leads work a live brief.'],
            ['time' => '16:00', 'title' => 'Readout', 'detail' => 'What held up, and what the audience would reject.'],
        ],
        'experiences' => [
            ['title' => 'Brief library', 'detail' => 'Anonymised collaborations, good and failed, on the wall.'],
            ['title' => 'Matching hours', 'detail' => 'Twenty-minute working meetings with a shared template.'],
        ],
        'speakers' => ['arjun-vale', 'anika-rao', 'noor-elias'],
        'sponsors' => ['aureum', 'orbit', 'northline'],
        'gallery' => ['images/events/brand-forum.jpg', 'images/gallery/workshop.jpg', 'images/gallery/creator-room.jpg'],
        'featured' => false,
    ],
    [
        'slug' => 'conclave-awards',
        'name' => 'Conclave Awards',
        'type' => 'Creator Awards',
        'location' => 'Assembly Hall, BKC, Mumbai',
        'city' => 'Mumbai',
        'date' => '21 November 2026',
        'dateShort' => '21 Nov 2026',
        'image' => 'images/events/awards.jpg',
        'summary' => 'A night that recognises craft, courage, and the work that changed how a community pays attention.',
        'about' => 'The Conclave Awards sit inside Summit weekend and stand on their own as a public night. Honours go to series, films, shows, and collaborations judged by a mixed room of creators, editors, and cultural critics. The point is recognition with a point of view.',
        'highlights' => [
            'Juries of creators, editors, and critics',
            'Categories for series, film, audio, and collaboration',
            'Performances between the honours',
        ],
        'schedule' => [
            ['time' => '18:30', 'title' => 'Reception', 'detail' => 'Nominees, partners, and the working press.'],
            ['time' => '19:30', 'title' => 'Ceremony', 'detail' => 'Honours, short films, and live performance.'],
            ['time' => '22:00', 'title' => 'After', 'detail' => 'A smaller room for the people who stayed.'],
        ],
        'experiences' => [
            ['title' => 'Nominee gallery', 'detail' => 'Stills and loops from the shortlisted work.'],
            ['title' => 'Live room', 'detail' => 'Music and performance between categories.'],
        ],
        'speakers' => ['leela-nair', 'rafael-mendes', 'mira-sen'],
        'sponsors' => ['aureum', 'lumen', 'vanta'],
        'gallery' => ['images/events/awards.jpg', 'images/gallery/red-carpet.jpg', 'images/gallery/celebration.jpg'],
        'featured' => false,
    ],
    [
        'slug' => 'storycraft-lab',
        'name' => 'Storycraft Lab',
        'type' => 'Workshops',
        'location' => 'Film Chamber, Hyderabad',
        'city' => 'Hyderabad',
        'date' => '6 February 2027',
        'dateShort' => '6 Feb 2027',
        'image' => 'images/events/storycraft.jpg',
        'summary' => 'A one-day workshop on series design, interview craft, and editing for people who publish weekly.',
        'about' => 'Storycraft is a working day. Participants bring a series, a pilot, or a stuck format. Faculty are practitioners — showrunners, editors, and hosts — and the afternoon is spent rewriting, not listening.',
        'highlights' => [
            'Small groups, real cuts on the table',
            'Interview and host craft',
            'A rewritten opening by the end of the day',
        ],
        'schedule' => [
            ['time' => '10:00', 'title' => 'Cold open', 'detail' => 'Why most series lose the audience in the first minute.'],
            ['time' => '13:00', 'title' => 'Studio blocks', 'detail' => 'Rewrite a cut with an editor in the room.'],
            ['time' => '16:30', 'title' => 'Playback', 'detail' => 'Groups show the new opening and defend it.'],
        ],
        'experiences' => [
            ['title' => 'Edit benches', 'detail' => 'Shared screens, headphones, and a faculty editor per table.'],
            ['title' => 'Host lab', 'detail' => 'On-camera notes for people who talk for a living.'],
        ],
        'speakers' => ['sana-iqbal', 'dev-menon', 'kabir-das'],
        'sponsors' => ['framehouse', 'kindred'],
        'gallery' => ['images/events/storycraft.jpg', 'images/gallery/workshop.jpg', 'images/gallery/camera-crew.jpg'],
        'featured' => false,
    ],
    [
        'slug' => 'coastline-sessions',
        'name' => 'Coastline Sessions',
        'type' => 'Influencer Meetups',
        'location' => 'Fort Aguada Grounds, Goa',
        'city' => 'Goa',
        'date' => '28 March 2027',
        'dateShort' => '28 Mar 2027',
        'image' => 'images/events/coastline.jpg',
        'summary' => 'A weekend meetup for creators who treat the feed as a publication, not a billboard.',
        'about' => 'Coastline is the looser room in the calendar: a meetup with a point of view. Talks stay short. The value is who is in the courtyard, what they are making next, and the collaborations that start because nobody is performing a keynote.',
        'highlights' => [
            'Short talks, long conversations',
            'Sunset sessions and a night programme',
            'Space for independent artists and hosts',
        ],
        'schedule' => [
            ['time' => '28 Mar · 15:00', 'title' => 'Arrival sessions', 'detail' => 'Three short talks, then the courtyard opens.'],
            ['time' => '28 Mar · 19:00', 'title' => 'Night programme', 'detail' => 'Live sets and a creator listening room.'],
            ['time' => '29 Mar · 11:00', 'title' => 'Morning walkthrough', 'detail' => 'Informal project shares before departure.'],
        ],
        'experiences' => [
            ['title' => 'Courtyard', 'detail' => 'The main room is outside, on purpose.'],
            ['title' => 'Listening room', 'detail' => 'Podcast and music creators play unfinished work.'],
        ],
        'speakers' => ['noor-elias', 'jules-fernando', 'mira-sen', 'dev-menon'],
        'sponsors' => ['pulse', 'kindred', 'vanta'],
        'gallery' => ['images/events/coastline.jpg', 'images/gallery/night-lights.jpg', 'images/gallery/live-crowd.jpg'],
        'featured' => false,
    ],
    [
        'slug' => 'after-hours',
        'name' => 'After Hours',
        'type' => 'Networking Events',
        'location' => 'Ballard Estate, Mumbai',
        'city' => 'Mumbai',
        'date' => '20 November 2026',
        'dateShort' => '20 Nov 2026',
        'image' => 'images/events/after-hours.jpg',
        'summary' => 'The off-record night of Summit weekend, for operators who would rather talk than post about it.',
        'about' => 'After Hours is a small networking night tied to Summit. No stage, no livestream, no sponsor reel on a loop. Producers, talent leads, editors, and founders use it to start the conversations the mainstage cannot hold.',
        'highlights' => [
            'Capped guest list',
            'No stage and no livestream',
            'Introductions hosted, not left to chance',
        ],
        'schedule' => [
            ['time' => '16:30', 'title' => 'Doors', 'detail' => 'Hosted introductions in the first hour.'],
            ['time' => '18:00', 'title' => 'Open floor', 'detail' => 'The room runs itself once people are placed.'],
            ['time' => '21:00', 'title' => 'Close', 'detail' => 'A hard end, so Summit morning still works.'],
        ],
        'experiences' => [
            ['title' => 'Hosted intros', 'detail' => 'A concierge matches people by what they are building.'],
            ['title' => 'Quiet rooms', 'detail' => 'Two side rooms for conversations that need a door.'],
        ],
        'speakers' => ['arjun-vale', 'anika-rao'],
        'sponsors' => ['northline', 'orbit'],
        'gallery' => ['images/events/after-hours.jpg', 'images/gallery/celebration.jpg', 'images/gallery/audience.jpg'],
        'featured' => false,
    ],
];

$eventTypes = [
    'All',
    'Creator Conferences',
    'YouTube Events',
    'Influencer Meetups',
    'Creator Awards',
    'Brand × Creator Events',
    'Workshops',
    'Networking Events',
];
