<?php

$homeContent = [
    'metaTitle' => 'Creators Conclave Summit 2026 | Creator & Influencer Awards Hyderabad',
    'metaDescription' => 'India’s creator summit, expo and CreatorX Awards for Telugu creators. December 2026, Hyderabad. Nominate now or book your pass.',
    'hero' => [
        'variant' => 'home',
        'eyebrow' => 'Explore excellence in',
        'title' => 'Creators Conclave Summit 2026',
        'dateStrong' => 'December 2026',
        'dateLight' => '2nd week',
        'venueStrong' => 'Hyderabad',
        'venueLight' => 'Venue TBA · Telangana, India',
        'image' => 'images/events/summit.jpg',
        'figure' => 'images/speakers/mira.jpg',
        'primary' => ['label' => 'Buy Your Pass', 'href' => 'passes.php'],
        'secondary' => ['label' => 'Nominate Now', 'href' => 'nominate.php'],
        'floatCards' => [
            ['label' => 'Interactive Session', 'title' => 'Summit Stage', 'meta' => 'Masterclasses & panels'],
            ['label' => 'Guest Stage', 'title' => 'CreatorX Night', 'meta' => '25+ award categories'],
        ],
    ],
    'banner' => [
        'image' => 'images/events/expo.jpg',
        'label' => 'Creators Conclave 2026',
        'kicker' => 'Summit',
    ],
    'about' => [
        'kicker' => 'About Event',
        'title' => 'Explore the Telugu creator economy',
        'text' => 'Creators Conclave is where Telugu creators from both states and across the world meet the brands, agencies and platforms that shape their growth. In one day you get a summit of ideas, an expo of opportunities and the CreatorX Awards — a night that celebrates the voices our audiences love.',
        'button' => 'Explore Us',
        'buttonHref' => 'about.php',
        'image' => 'images/events/masterclass.jpg',
    ],
    'why' => [
        'title' => 'Why You Should Join The Event?',
        'items' => [
            [
                'title' => 'Get Discovered',
                'text' => 'Put your work in front of brands actively looking for creators across every niche.',
                'icon' => '01',
                'link' => ['label' => 'Read More', 'href' => 'about.php'],
            ],
            [
                'title' => 'New Knowledge',
                'text' => 'Learn growth, monetisation and brand partnerships from 12 industry experts.',
                'icon' => '02',
                'link' => ['label' => 'Read More', 'href' => 'events.php'],
            ],
            [
                'title' => 'Idea Sharing',
                'text' => 'Meet fellow creators, agencies and OTT teams for your next collaboration.',
                'icon' => '03',
                'link' => ['label' => 'Read More', 'href' => 'sponsor.php'],
            ],
        ],
    ],
    'venue' => [
        'kicker' => 'Event Venue',
        'title' => 'Get the best experience in the world of creators',
        'text' => 'One room for summit sessions, an expo of 100+ brands, and a night of CreatorX Awards — built for people who publish, produce and partner.',
        'date' => 'December 2026 (2nd week)',
        'time' => 'Full-day programme',
        'place' => 'Hyderabad [venue TBA]',
        'address' => 'Telangana, India',
    ],
    'schedule' => [
        'tabs' => [
            [
                'id' => 'day-1',
                'label' => 'Summit',
                'date' => 'Day programme',
                'items' => [
                    [
                        'type' => 'Keynote',
                        'time' => 'Opening',
                        'date' => 'Summit',
                        'title' => 'Opening Keynote',
                        'speaker' => 'Industry leaders',
                        'role' => 'Creator economy',
                        'text' => 'The rise of the Telugu creator economy, told by the people who built audiences the industry now has to take seriously.',
                        'image' => 'images/events/masterclass.jpg',
                        'href' => 'events.php',
                    ],
                    [
                        'type' => 'Panel',
                        'time' => 'Mid-morning',
                        'date' => 'Summit',
                        'title' => 'Brands × Creators',
                        'speaker' => 'Working panel',
                        'role' => 'Collaborations',
                        'text' => 'What makes a collaboration hold: disclosure, taste, timelines, and an audience that has to trust both sides.',
                        'image' => 'images/events/brand-forum.jpg',
                        'href' => 'events.php',
                    ],
                    [
                        'type' => 'Masterclass',
                        'time' => 'Afternoon',
                        'date' => 'Summit',
                        'title' => 'Craft Masterclass',
                        'speaker' => 'Faculty creators',
                        'role' => 'Grow & monetise',
                        'text' => 'A working session on formats, series, and the business of an audience, taught by people who still publish.',
                        'image' => 'images/events/storycraft.jpg',
                        'href' => 'events.php',
                    ],
                ],
            ],
            [
                'id' => 'day-2',
                'label' => 'Expo',
                'date' => 'Floor day',
                'items' => [
                    [
                        'type' => 'Expo',
                        'time' => 'All day',
                        'date' => 'Expo',
                        'title' => 'The Expo Floor',
                        'speaker' => '100+ zones',
                        'role' => 'Brands & startups',
                        'text' => 'Brand, agency, startup, and OTT floors where a conversation can become a brief before the day is over.',
                        'image' => 'images/events/expo.jpg',
                        'href' => 'events.php',
                    ],
                    [
                        'type' => 'Meetup',
                        'time' => 'Evening',
                        'date' => 'Expo',
                        'title' => 'Creator Meet-ups',
                        'speaker' => 'Hosted introductions',
                        'role' => 'Networking',
                        'text' => 'Creators, agencies, and brand teams in one room. Short talks, and the longer conversations that follow.',
                        'image' => 'images/events/meetups.jpg',
                        'href' => 'events.php',
                    ],
                ],
            ],
            [
                'id' => 'day-3',
                'label' => 'Awards',
                'date' => 'Night',
                'items' => [
                    [
                        'type' => 'Awards',
                        'time' => 'Evening',
                        'date' => 'CreatorX',
                        'title' => 'CreatorX Awards',
                        'speaker' => 'Red carpet night',
                        'role' => '25+ categories',
                        'text' => 'Red carpet, performances, and 25+ categories for the Telugu creators setting the standard on every platform.',
                        'image' => 'images/events/awards.jpg',
                        'href' => 'awards.php',
                    ],
                    [
                        'type' => 'After hours',
                        'time' => 'Late',
                        'date' => 'CreatorX',
                        'title' => 'After the Honours',
                        'speaker' => 'Celebration',
                        'role' => 'Creators & guests',
                        'text' => 'The floor after dark — celebrations, cameras, and the conversations that start when the awards are done.',
                        'image' => 'images/events/after-hours.jpg',
                        'href' => 'awards.php',
                    ],
                ],
            ],
        ],
    ],
    'countdown' => [
        'kicker' => 'Countdown',
        'title' => 'Countdown Until the Event. Register Now',
    ],
    'speakers' => [
        'kicker' => 'Speakers',
        'title' => 'Our Amazing & Learned Event Speakers',
    ],
    'marquee' => ['Create', 'Collab', 'Conquer', 'Summit', 'Expo', 'Awards'],
    'pricing' => [
        'kicker' => 'Ticket Pricing',
        'title' => 'Event Pass & Tickets',
        'text' => 'One pass. A full day of sessions, an expo of 100+ brands, and a seat at the CreatorX Awards.',
        'passes' => [
            [
                'name' => 'Silver Pass',
                'price' => '₹[ ]',
                'unit' => '/person',
                'note' => 'For one person ticket',
                'features' => ['Summit sessions', 'Expo access', 'Awards night seating', 'QR e-ticket', 'GST invoice'],
                'featured' => false,
            ],
            [
                'name' => 'Gold Pass',
                'price' => '₹[ ]',
                'unit' => '/person',
                'note' => 'For one person ticket',
                'features' => ['Everything in Silver', 'Priority seating', 'Networking lounge', 'Welcome kit', 'GST invoice'],
                'featured' => true,
            ],
            [
                'name' => 'Platinum Pass',
                'price' => '₹[ ]',
                'unit' => '/person',
                'note' => 'For one person ticket',
                'features' => ['Everything in Gold', 'VIP front-row', 'Jury meet-and-greet', 'Dinner access', 'GST invoice'],
                'featured' => false,
            ],
        ],
    ],
    'partners' => [
        'kicker' => 'Partners',
        'title' => 'Partners who collaborate with us',
    ],
    'testimonials' => [
        [
            'quote' => 'Creators Conclave puts brands, agencies and creators in one room with a clear brief — the conversations that usually take weeks start before lunch.',
            'name' => 'Ananya Reddy',
            'place' => 'Hyderabad',
            'avatar' => 'images/speakers/leela.jpg',
            'figure' => 'images/speakers/arjun.jpg',
            'rating' => 5,
        ],
        [
            'quote' => 'From the summit floor to awards night, the programme is built for people who still publish. That is rare, and it shows.',
            'name' => 'Karthik Rao',
            'place' => 'Telangana',
            'avatar' => 'images/speakers/kabir.jpg',
            'figure' => 'images/speakers/dev.jpg',
            'rating' => 5,
        ],
    ],
    'faq' => [
        'title' => 'Do You Have any questions about the event?',
        'text' => 'Discussing growth, monetisation, brand deals and the awards that recognise Telugu creators.',
        'button' => 'Buy Your Pass',
        'buttonHref' => 'passes.php',
        'items' => [
            [
                'q' => 'When and where is the summit?',
                'a' => 'December 2026 (2nd week) in Hyderabad. Exact date and venue will be announced soon.',
            ],
            [
                'q' => 'Who can nominate for CreatorX Awards?',
                'a' => 'Any creator of Telugu origin from Andhra Pradesh, Telangana or abroad (NRI), active on any social media platform.',
            ],
            [
                'q' => 'What is included in a pass?',
                'a' => 'Summit sessions, expo access and awards night seating. Gold and Platinum add lounges, kits and VIP access.',
            ],
            [
                'q' => 'How do brands get involved?',
                'a' => 'Through sponsorship, an expo stall, or brand-creator collaborations. Visit Sponsor & Exhibit to enquire.',
            ],
        ],
    ],
    'moments' => [
        'kicker' => 'In the room',
        'title' => 'Why You Should Join The Event?',
    ],
    'newsletter' => [
        'title' => 'Stay Tuned with weekly Newsletter',
        'note' => 'No worries, we won’t spam your inbox',
        'button' => 'Subscribe',
    ],
    'footerCta' => [
        'title' => 'Join India’s biggest creator community',
        'partner' => 'Be a partner',
        'partnerHref' => 'sponsor.php',
        'ticket' => 'Buy Your Pass',
        'ticketHref' => 'passes.php',
    ],
    'numbers' => [
        ['value' => 1000, 'suffix' => '+', 'label' => 'Creators'],
        ['value' => 3000, 'suffix' => '+', 'label' => 'Audience'],
        ['value' => 100, 'suffix' => '+', 'label' => 'Brands'],
    ],
];
