<?php

$speakers = [
    [
        'slug' => 'mira-sen',
        'name' => 'Mira Sen',
        'category' => 'YouTubers',
        'platform' => 'YouTube',
        'role' => 'Culture essays & city films',
        'image' => 'images/speakers/mira.jpg',
        'bio' => 'Mira makes long cultural essays watched by people who still finish a video. She is opening Summit with a talk on taste after the algorithm.',
    ],
    [
        'slug' => 'arjun-vale',
        'name' => 'Arjun Vale',
        'category' => 'Entrepreneurs',
        'platform' => 'Stage & studio',
        'role' => 'Founder, Vale & Co.',
        'image' => 'images/speakers/arjun.jpg',
        'bio' => 'Arjun builds tools for independent shows. He advises creators on rights, crews, and how not to sell the format with the sponsorship.',
    ],
    [
        'slug' => 'leela-nair',
        'name' => 'Leela Nair',
        'category' => 'Podcasters',
        'platform' => 'Audio',
        'role' => 'Host, The Long Take',
        'image' => 'images/speakers/leela.jpg',
        'bio' => 'Leela’s interview show is a reference for patience. She chairs the awards jury for audio and will teach a host lab in Hyderabad.',
    ],
    [
        'slug' => 'kabir-das',
        'name' => 'Kabir Das',
        'category' => 'YouTubers',
        'platform' => 'YouTube',
        'role' => 'Explainers & field pieces',
        'image' => 'images/speakers/kabir.jpg',
        'bio' => 'Kabir’s channel treats reporting as entertainment without sanding off the reporting. He leads the format clinic at Creators Night.',
    ],
    [
        'slug' => 'noor-elias',
        'name' => 'Noor Elias',
        'category' => 'Influencers',
        'platform' => 'Instagram & film',
        'role' => 'Fashion, travel, short film',
        'image' => 'images/speakers/noor.jpg',
        'bio' => 'Noor moves between campaigns and short films. At the Brand Forum she argues for collaborations that can survive a second viewing.',
    ],
    [
        'slug' => 'dev-menon',
        'name' => 'Dev Menon',
        'category' => 'Artists',
        'platform' => 'Music & live',
        'role' => 'Composer and performer',
        'image' => 'images/speakers/dev.jpg',
        'bio' => 'Dev scores creator films and plays the Awards and Coastline nights. He talks about sound as part of the edit, not a bed underneath it.',
    ],
    [
        'slug' => 'sana-iqbal',
        'name' => 'Sana Iqbal',
        'category' => 'Digital Creators',
        'platform' => 'YouTube & classrooms',
        'role' => 'Series producer',
        'image' => 'images/speakers/sana.jpg',
        'bio' => 'Sana produces weekly series for independent hosts. Storycraft Lab is her room: cold opens, release cadence, and crews that last.',
    ],
    [
        'slug' => 'rafael-mendes',
        'name' => 'Rafael Mendes',
        'category' => 'Speakers',
        'platform' => 'Stage',
        'role' => 'Critic and moderator',
        'image' => 'images/speakers/rafael.jpg',
        'bio' => 'Rafael moderates the conversations that do not flatter the room. He has spent a decade writing about attention, fame, and the internet’s manners.',
    ],
    [
        'slug' => 'anika-rao',
        'name' => 'Anika Rao',
        'category' => 'Entrepreneurs',
        'platform' => 'Brand & partnerships',
        'role' => 'Partner, Northline',
        'image' => 'images/speakers/anika.jpg',
        'bio' => 'Anika runs cultural partnerships for a media house that still employs editors. She designs the Forum’s matching hours.',
    ],
    [
        'slug' => 'jules-fernando',
        'name' => 'Jules Fernando',
        'category' => 'Digital Creators',
        'platform' => 'Short film & YouTube',
        'role' => 'Director',
        'image' => 'images/speakers/jules.jpg',
        'bio' => 'Jules directs films that begin as YouTube series. He is at Creators Night and Coastline to talk about finishing, not just posting.',
    ],
];

$speakerCategories = [
    'All',
    'YouTubers',
    'Influencers',
    'Entrepreneurs',
    'Speakers',
    'Podcasters',
    'Artists',
    'Digital Creators',
];
